### ISSUE TITLE
HTML comment left ligature

### ISSUE THREAD

**Issue by natewind** [rojiani/Ligaturizer#12]
It’s off to the left and also bold (at least in Ubuntu Mono).
![screenshot](https://user-images.githubusercontent.com/30814650/35449398-f09b9790-02cd-11e8-8d67-dc23dc22a962.png)

**Comment by natewind** [comment]
“www” has the same problem.

**Comment by ToxicFrog** [comment]
I can't reproduce the bold issue, but I can reproduce the cutting off -- some other wide ligatures like `<==` demonstrate it as well. It's less obvious in my preferred font (Cousine) but can be reproduced there with `<!--` in certain environments.

At a guess, these fonts use narrower characters than Fira Code does, so when the Fira glyphs are em-scaled, they end up the correct height, but too wide.

It might be possible to mitigate this by using `transform()` to horizontally scale the ligature glyphs to match the em-width of the font they're being inserted into, and updating the horizontal advance to match; I'll look into that.

**Comment by ToxicFrog** [comment]
Since I can't reproduce the bold issue, I can't address it, but I do have a fix in the works for the scaling, which should hopefully be ready for testing sometime this weekend.

**Comment by ToxicFrog** [comment]
7d19d31 should address this; try the Ubuntu Mono from it and let me know if it works.
