### ISSUE TITLE
Screenshots colorscheme

### ISSUE THREAD

**Issue by alexozer** [rojiani/Ligaturizer#17]
I hate to be the one to ask, but which colorscheme does the screenshots in the README use?

**Comment by rojiani** [comment]
Its using my own custom theme - you can get it here:
[IntelliJ](https://github.com/rojiani/ziggy-stardust-intellij-color-scheme) - The ligaturizer screenshots are probably closest to [Version 2](https://github.com/rojiani/ziggy-stardust-intellij-color-scheme/blob/master/ZiggyStardust-v2.icls)
[Atom](https://github.com/rojiani/dev-setup/tree/master/Atom/packages/ziggy-stardust-syntax)
[Sublime](https://github.com/rojiani/dev-setup/blob/master/SublimeText/shared/ColorSchemes/ZiggyStardust.tmTheme)
[VS Code](https://github.com/rojiani/dev-setup/tree/master/VisualStudioCode/extensions/ziggy-stardust)
[iTerm](https://github.com/rojiani/dev-setup/blob/master/iTerm/ColorSchemes/ZiggyStardust.itermcolors)
[XCode](https://github.com/rojiani/dev-setup/blob/master/Xcode/FontAndColorThemes/ZiggyStardust.xccolortheme)

**Comment by alexozer** [comment]
Neat thank you

**Comment by cedrickring** [comment]
Unfortunately all links are down... Can you re-post it? 💯

**Comment by rojiani** [comment]
@cedrickring Here you go: now all in one place - [ziggy-stardust-colors](https://github.com/rojiani/ziggy-stardust-colors)

**Comment by cedrickring** [comment]
Thanks alot 👍
