### ISSUE TITLE
Add Fantasque Sans Mono to the repository

### ISSUE THREAD

**Issue by fer22f** [rojiani/Ligaturizer#20]
It would be nice to have a handy download for a ligaturized version of https://github.com/belluzj/fantasque-sans!

**Comment by rojiani** [comment]
Added.

Ligaturized versions are here:
[FantasqueSansMono-NoLoopK](https://github.com/rojiani/Ligaturizer/tree/master/output-fonts/FantasqueSansMono-NoLoopK)
[FantasqueSansMono-Normal](https://github.com/rojiani/Ligaturizer/tree/master/output-fonts/FantasqueSansMono-Normal)
