### ISSUE TITLE
Ligatures not rendering in iTerm

### ISSUE THREAD

**Issue by kyleholzinger** [rojiani/Ligaturizer#4]
Not sure if this is really an issue with this repo, but I tried using this font in iTerm and the ligatures aren't working in iTerm. Is there some other setup necessary? I tried using it in my editor and it seemed to be fine strangely enough

**Comment by rojiani** [comment]
There's a few things to check:

1. What version of iTerm are you using? iTerm added support for ligatures not too long ago. Try updating.
2. If ligatures are enabled: Go to `Preferences ( ⌘ , ) -> Profiles -> Text`, then under **Font** make sure the `Enable Ligatures` checkbox is checked.

Fonts generated by the script should generally work in iTerm. I tried out each one, and they all work except for SF Mono. For SF Mono, the "Enable Ligatures" option is disabled - greyed out & can't be selected. I'm not sure why that is.

If you are still have the problem after trying the 2 things above, let me know

**Comment by kyleholzinger** [comment]
Hm I'm on latest nightly. And yeah I have that setting enabled

**Comment by kyleholzinger** [comment]
What's strange is that it works fine in RubyMine and SublimeText, it's _only_ in iTerm that it doesn't work

**Comment by delphinus** [comment]
I also found this problem with iTerm 3.1.5 (the latest release) and SF Mono in this repo.

And Preferences in iTerm2 shows `Use Ligatures` unselectable.

<img width="277" alt="2018-01-14 17 00 13" src="https://user-images.githubusercontent.com/1239245/34913964-c6ac706a-f94c-11e7-854c-fdd93ed215de.png">

For instance, it shows selectable with [Iosevka](https://be5invis.github.io/Iosevka/).

<img width="258" alt="2018-01-14 17 00 02" src="https://user-images.githubusercontent.com/1239245/34913969-e7c3631c-f94c-11e7-92a4-3393657b7454.png">

**Comment by rojiani** [comment]
I tried this with the newest ligaturized version of [SF Mono](https://github.com/rojiani/Ligaturizer/blob/master/output-fonts/LigaSFMono-Regular.ttf) and the "Use Ligatures" checkbox is now enabled. The underlying issue must have been fixed by [ones of these changes](https://github.com/rojiani/Ligaturizer/pull/11).

**Comment by kyleholzinger** [comment]
Sweet yep, all good now! Just pulled again and it's fixed. Thanks so much! I'm stoked to be able to use these with ligatures in my terminal 👍
