### ISSUE TITLE
Create a branch in the Repo

### ISSUE THREAD

**Issue by vikky49** [rojiani/Ligaturizer#5]
HI 

I added more ligatures to the script and if i want to create a Pull Request would u be interested ? And I dont see an option to create branches ? Is there a permission

**Comment by karambaq** [comment]
Hey, @vikky49 I'm interesting in that

**Comment by rojiani** [comment]
@vikky49 @karambaq Sorry for the very delayed response, I'd definitely be interested. I've invited both of you as Collaborators, and only have the master branch set as protected...from the GitHub documentation I think you should be able to do anything except push to master (requires a PR). Let me know if you still don't have access.
