### ISSUE TITLE
[Feature request] Allow standard input for scripted operation

### ISSUE THREAD

**Issue by jonathonf** [rojiani/Ligaturizer#7]
Currently the script prompts for an input file.

It would be great if I could pass it a filename directly so the process can be scripted.

**Comment by ToxicFrog** [comment]
If you're comfortable patching `ligaturize.py` this isn't hard -- just read `sys.argv` like any other python program. `[0]` will be `ligaturize.py` and everything after that will be the subsequent arguments.

You can also just pipe the answers to the questions it asks into it using echo or printf:
```
printf '%s\n%s\n' 'Cousine-Regular.ttf' 'CousineLigatures-Regular.ttf' | fontforge -lang=py ligatureize.py`
```

**Comment by rojiani** [comment]
[Fixed](https://github.com/rojiani/Ligaturizer/pull/11) - see Makefile
