### ISSUE TITLE
Can  use regular variant of FiraCode?

### ISSUE THREAD

**Issue by haktrik** [rojiani/Ligaturizer#8]
I've tried to use regular FiraCode as source of ligatures, however I'm receiving error:
![image](https://user-images.githubusercontent.com/32274737/34737274-00fead58-f576-11e7-8630-38140726db3f.png)

**Comment by ToxicFrog** [comment]
Ligaturize was written for an older version of Fira Code that has different ligatures. A quick and dirty way to get it working is to comment out the ligatures that it can't find, in this case equal_asciitilde.

**Comment by rojiani** [comment]
What @ToxicFrog said is correct. I started working on upgrading to the latest version of Fira Code today, and will be adding support for different font widths after that.

**Comment by ToxicFrog** [comment]
I already have patches for that, so don't sink too much time into it yet :) Should be able to create a PR later today.

**Comment by rojiani** [comment]
[Fixed](https://github.com/rojiani/Ligaturizer/pull/11). Thanks for you contrib @ToxicFrog!
